"""add email subject to leads

Revision ID: 4ac1909e4f96
Revises: c1e60ed4738a
Create Date: 2026-06-09 10:49:58.420205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac1909e4f96'
down_revision: Union[str, Sequence[str], None] = 'c1e60ed4738a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('email_subject', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'email_subject')
    # ### end Alembic commands ###
