"""make email_subject nullable

Revision ID: d13b9e8a4a3f
Revises: 4ac1909e4f96
Create Date: 2026-06-09 11:15:42.186799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13b9e8a4a3f'
down_revision: Union[str, Sequence[str], None] = '4ac1909e4f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
